workflows:
  ios-release:
    name: VCenter iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      groups:
        - ios-release
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dnzteam.vcenter
        # Codemagic سيختار تلقائياً DIST_CERT و DIST_PROFILE
        # بناءً على bundle_identifier و distribution_type
      
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        # App Store Connect API credentials
        # يجب إضافة هذه القيم في Codemagic UI: Environment variables
        APP_STORE_CONNECT_ISSUER_ID: dca6b398-f004-41b8-98ce-ef6553d892ea
        APP_STORE_CONNECT_KEY_IDENTIFIER: 5RU583BNQ3
        # APP_STORE_CONNECT_PRIVATE_KEY سيتم إضافته كـ secure variable
      
      flutter: stable
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -f Podfile.lock
          pod repo update
          pod install --repo-update
      
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Verify code signing setup
        script: |
          # التحقق من أن provisioning profiles تم تطبيقها بشكل صحيح
          echo "✅ Code signing setup completed"
      
      - name: Set up Firebase (if needed)
        script: |
          # Firebase config files should be in the repository
          # ios/Runner/GoogleService-Info.plist
          # android/app/google-services.json
          echo "✅ Firebase config files already in repository"
      
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
      
      - name: Ensure App Store Connect key env
        script: |
          if [ -z "${APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY}" ] && [ -n "${APP_STORE_CONNECT_PRIVATE_KEY}" ]; then
            export APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY="${APP_STORE_CONNECT_PRIVATE_KEY}"
            echo "APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY populated from APP_STORE_CONNECT_PRIVATE_KEY"
          fi
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - jaafar.albanaa@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        # استخدام مفاتيح App Store Connect عبر متغيرات البيئة
        api_key: $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

